/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.concepter.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.JToggleButton;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import org.apache.commons.lang3.StringUtils;

import com.mxgraph.model.mxCell;
import com.mxgraph.swing.mxGraphOutline;
import com.mxgraph.util.mxCellRenderer;
import com.mxgraph.util.mxEvent;
import com.mxgraph.util.mxEventObject;
import com.mxgraph.util.mxEventSource.mxIEventListener;
import com.mxgraph.view.mxGraph;

import br.com.concepter.controller.ConceptERController;
import br.com.concepter.model.enuns.TipoAtributoEnum;
import br.com.concepter.model.enuns.TipoEntidadeEnum;
import br.com.concepter.model.enuns.TipoEspecializacaoEnum;
import br.com.concepter.utils.XmlUtils;


public class TelaPrincipal extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form TelaPrincipal
	 */

	private static int botao;
	private static TipoAtributoEnum tipoAtributo;
	private static TipoEspecializacaoEnum tipoEspecializacao;
	private static TipoEntidadeEnum tipoEntidade;
	
	/**
	 * Flag indicating whether the current graph has been modified 
	 */
	protected boolean modified = false;

	public static String PATH_FILE = "";

	private static ConceptERController controller = new ConceptERController();


	public TelaPrincipal() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(TelaPrincipal.class.getResource("/br/com/concepter/view/resources/imagens/structure.png"))); 
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
		areaGrafica = new br.com.concepter.view.AreaGrafica();
		jToolBar1 = new javax.swing.JToolBar();
		jSeparator22 = new javax.swing.JToolBar.Separator();
		jToggleButton1 = new javax.swing.JToggleButton();
		jSeparator8 = new javax.swing.JToolBar.Separator();
		jToggleButton2 = new javax.swing.JToggleButton();
		jSeparator3 = new javax.swing.JToolBar.Separator();
		jSeparator18 = new javax.swing.JToolBar.Separator();
		jToggleButton3 = new javax.swing.JToggleButton();
		jSeparator10 = new javax.swing.JToolBar.Separator();
		jToggleButton4 = new javax.swing.JToggleButton();
		jSeparator11 = new javax.swing.JToolBar.Separator();
		jToggleButton5 = new javax.swing.JToggleButton();
		jSeparator7 = new javax.swing.JToolBar.Separator();
		jToggleButton6 = new javax.swing.JToggleButton();
		jSeparator9 = new javax.swing.JToolBar.Separator();
		jToggleButton7 = new javax.swing.JToggleButton();
		jSeparator4 = new javax.swing.JToolBar.Separator();
		jSeparator20 = new javax.swing.JToolBar.Separator();
		jToggleButton8 = new javax.swing.JToggleButton();
		jSeparator13 = new javax.swing.JToolBar.Separator();
		jToggleButton9 = new javax.swing.JToggleButton();
		jSeparator12 = new javax.swing.JToolBar.Separator();
		jToggleButton10 = new javax.swing.JToggleButton();
		jSeparator5 = new javax.swing.JToolBar.Separator();
		jSeparator19 = new javax.swing.JToolBar.Separator();
		jToggleButton11 = new javax.swing.JToggleButton();
		jSeparator17 = new javax.swing.JToolBar.Separator();
		jToggleButton12 = new javax.swing.JToggleButton();
		jSeparator6 = new javax.swing.JToolBar.Separator();
		jSeparator21 = new javax.swing.JToolBar.Separator();
		jToggleButton13 = new javax.swing.JToggleButton();
		jSeparator16 = new javax.swing.JToolBar.Separator();
		jToggleButton14 = new javax.swing.JToggleButton();
		//jSeparator15 = new javax.swing.JToolBar.Separator();
		jToggleButton15 = new javax.swing.JToggleButton();
		//jSeparator14 = new javax.swing.JToolBar.Separator();
		jToggleButton16 = new javax.swing.JToggleButton();
		jSeparator23 = new javax.swing.JToolBar.Separator();
		jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JPopupMenu.Separator();
		jMenuItem7 = new javax.swing.JMenuItem();
		jSeparator2 = new javax.swing.JPopupMenu.Separator();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();

		jButton1.setText("jButton1");

		jRadioButtonMenuItem1.setSelected(true);
		jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

		setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				Object[] options = { "Salvar", "Não Salvar", "Cancelar" };
				int ret = JOptionPane.showOptionDialog(null, "Suas alterações serão perdidas se não forem salvas", "ConceptER",
						JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, 
						options, options[0]);
				if(ret == JOptionPane.OK_OPTION){
					JFileChooser jfc = new JFileChooser();

					if(StringUtils.isEmpty(PATH_FILE)) {
						if(jfc.showSaveDialog(jMenu1) == JFileChooser.APPROVE_OPTION){
							PATH_FILE = jfc.getSelectedFile().getPath() ;				
						}	
					}
					if(controller.save(areaGrafica, PATH_FILE)) {
						setVisible(false);
						dispose();
					}

				} else if (ret == JOptionPane.NO_OPTION) {
					setVisible(false);
					dispose();
				}
			}
		});

		setTitle("ConceptER");
		setLocationByPlatform(true);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}
		});

		areaGrafica.setBackground(java.awt.Color.white);
		areaGrafica.setBorder(null);
		areaGrafica.setForeground(new java.awt.Color(255, 255, 255));
		areaGrafica.setPreferredSize(new java.awt.Dimension(400, 200));
		areaGrafica.setVisible(true);

		jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
		jToolBar1.setRollover(true);
		jToolBar1.setAlignmentY(0.0F);
		jToolBar1.setMinimumSize(new Dimension(40, 209));
		jToolBar1.setPreferredSize(new Dimension(40, 209));
		jToolBar1.add(jSeparator22);

		jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retanguloo.jpg"))); // NOI18N
		jToggleButton1.setToolTipText("Entidade");
		jToggleButton1.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton1);
				jToggleButton1ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton1);
		jToolBar1.add(jSeparator8);

		jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retangulo.png"))); // NOI18N
		jToggleButton2.setToolTipText("Entidade Fraca");
		jToggleButton2.setFocusable(false);
		jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton2.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton2);
				jToggleButton2ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton2);
		jToolBar1.add(jSeparator3);
		jToolBar1.add(jSeparator18);

		jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Circulo.png"))); // NOI18N
		jToggleButton3.setToolTipText("Atributo Simples");
		jToggleButton3.setFocusable(false);
		jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton3.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton3);
				jToggleButton3ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton3);
		jToolBar1.add(jSeparator10);

		jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Circulo com traço.png"))); // NOI18N
		jToggleButton4.setToolTipText("Atributo Chave");
		jToggleButton4.setFocusable(false);
		jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton4.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton4);
				jToggleButton4ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton4);
		jToolBar1.add(jSeparator11);

		jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/3 balões.png"))); // NOI18N
		jToggleButton5.setToolTipText("Atributo Composto");
		jToggleButton5.setFocusable(false);
		jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton5.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton5);
				jToggleButton5ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton5);
		jToolBar1.add(jSeparator7);

		jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Circulo dentro.png"))); // NOI18N
		jToggleButton6.setToolTipText("Atributo Multivalorado");
		jToggleButton6.setFocusable(false);
		jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton6.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton6);
				jToggleButton6ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton6);
		jToolBar1.add(jSeparator9);

		jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Circulo tracejado.png"))); // NOI18N
		jToggleButton7.setToolTipText("Atributo Derivado");
		jToggleButton7.setFocusable(false);
		jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton7.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton7);
				jToggleButton7ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton7);
		jToolBar1.add(jSeparator4);
		jToolBar1.add(jSeparator20);

		jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/binario.png"))); // NOI18N
		jToggleButton8.setToolTipText("Relacionamento Binário");
		jToggleButton8.setFocusable(false);
		jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton8.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton8);
				jToggleButton8ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton8);
		jToolBar1.add(jSeparator13);

		jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/ternario.png"))); // NOI18N
		jToggleButton9.setToolTipText("Relacionamento Ternário");
		jToggleButton9.setFocusable(false);
		jToggleButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton9.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton9);
				jToggleButton9ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton9);
		jToolBar1.add(jSeparator12);

		jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/quaternario.png"))); // NOI18N
		jToggleButton10.setToolTipText("Relacionamento Quaternário");
		jToggleButton10.setFocusable(false);
		jToggleButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton10.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton10);
				jToggleButton10ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton10);
		jToolBar1.add(jSeparator5);
		jToolBar1.add(jSeparator19);
		
	
		jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Círculo C.png"))); // NOI18N
		jToggleButton16.setToolTipText("Especialização");
		jToggleButton16.setFocusable(false);
		jToggleButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton16.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton16);
				jToggleButton16ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton16);
		jToolBar1.add(jSeparator23);


		jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/CirculoD.png"))); // NOI18N
		jToggleButton11.setToolTipText("Disjunção");
		jToggleButton11.setFocusable(false);
		jToggleButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton11.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton11);
				jToggleButton11ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton11);
		jToolBar1.add(jSeparator17);

		jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Círculo O.png"))); // NOI18N
		jToggleButton12.setToolTipText("Sobreposição");
		jToggleButton12.setFocusable(false);
		jToggleButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton12.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton12);
				jToggleButton12ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton12);
		jToolBar1.add(jSeparator6);
		jToolBar1.add(jSeparator21);

		jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retangulo losango.jpg"))); // NOI18N
		jToggleButton13.setToolTipText("Agregação");
		jToggleButton13.setFocusable(false);
		jToggleButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton13.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton13);
				jToggleButton13ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton13);
		jToolBar1.add(jSeparator16);
		/*
		jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retangulo losango.jpg"))); // NOI18N
		jToggleButton14.setToolTipText("Agregação Ternária");
		jToggleButton14.setFocusable(false);
		jToggleButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton14.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton14);
				jToggleButton14ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton14);
		jToolBar1.add(jSeparator15);

		jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retangulo losango.jpg"))); // NOI18N
		jToggleButton15.setToolTipText("Agregação Quaternária");
		jToggleButton15.setFocusable(false);
		jToggleButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jToggleButton15.setPreferredSize(new java.awt.Dimension(34, 23));
		jToggleButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onlyOneButtonPressed(jToggleButton15);
				jToggleButton15ActionPerformed(evt);
			}
		});
		jToolBar1.add(jToggleButton15);
		jToolBar1.add(jSeparator14);
        */
		jMenu1.setText("Arquivo");

		jMenuItem1.setText("Novo");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("Abrir ...");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem4.setText("Salvar");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem4);

		jMenuItem5.setText("Salvar como ...");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem5);
		jMenu1.add(jSeparator1);

		jMenuItem7.setText("Exportar imagem ...");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem7);
		jMenu1.add(jSeparator2);

		jMenuItem8.setText("Sair");
		jMenuItem8.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				setVisible(false);
				dispose();
				
			}
		});
		jMenu1.add(jMenuItem8);

		jMenuBarTelaPrincipal.add(jMenu1);

		jMenu2.setText("Ferramenta");

		jMenuBarTelaPrincipal.add(jMenu2);
		
		mntmOpcoes = new JMenuItem("Opções");
		mntmOpcoes.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				mntmOpcoesActionPerformed(evt);
			}
		});
		jMenu2.add(mntmOpcoes);

		jMenu3.setText("Ajuda");

		jMenuItem3.setText("Sobre");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem3);

		jMenuBarTelaPrincipal.add(jMenu3);

		setJMenuBar(jMenuBarTelaPrincipal);

		// Creates the graph outline component
		graphOutline = new mxGraphOutline(areaGrafica.getAreaGrafico());

		// Creates the inner split pane that contains the library with the
		// palettes and the graph outline on the left side of the window
		JSplitPane inner = new JSplitPane(JSplitPane.VERTICAL_SPLIT,
				jToolBar1, graphOutline);
		inner.setOneTouchExpandable(true);
		inner.setDividerLocation(550);
		inner.setResizeWeight(1);
		inner.setDividerSize(7);
		inner.setBorder(null);
		
		// Do not change the scale and translation after files have been loaded
		areaGrafica.getAreaGrafico().getGraph().setResetViewOnRootChange(false);

		// Updates the modified flag if the graph model changes
		areaGrafica.getAreaGrafico().getGraph().getModel().addListener(mxEvent.CHANGE, changeTracker);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(2, 2, 2)
						.addComponent(inner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(areaGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(inner, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
						.addContainerGap())
				.addComponent(areaGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * 
	 */
	protected mxIEventListener changeTracker = new mxIEventListener()
	{
		public void invoke(Object source, mxEventObject evt)
		{
			setModified(true);
		}
	};
	
	/**
	 * 
	 * @param modified
	 */
	public void setModified(boolean modified)
	{
		boolean oldValue = this.modified;
		this.modified = modified;

		firePropertyChange("modified", oldValue, modified);

		if (oldValue != modified)
		{
			//updateTitle();
		}
	}

	public static void desclicarBotoes(){
		TelaPrincipal.jToggleButton1.setSelected(false);
		TelaPrincipal.jToggleButton2.setSelected(false);
		TelaPrincipal.jToggleButton3.setSelected(false);
		TelaPrincipal.jToggleButton4.setSelected(false);
		TelaPrincipal.jToggleButton5.setSelected(false);
		TelaPrincipal.jToggleButton6.setSelected(false);
		TelaPrincipal.jToggleButton7.setSelected(false);
		TelaPrincipal.jToggleButton8.setSelected(false);
		TelaPrincipal.jToggleButton9.setSelected(false);
		TelaPrincipal.jToggleButton10.setSelected(false);
		TelaPrincipal.jToggleButton11.setSelected(false);
		TelaPrincipal.jToggleButton12.setSelected(false);
		TelaPrincipal.jToggleButton13.setSelected(false);
		TelaPrincipal.jToggleButton14.setSelected(false);
		TelaPrincipal.jToggleButton15.setSelected(false);
		TelaPrincipal.jToggleButton16.setSelected(false);
	}
	
	public static int getBotao(){
		return TelaPrincipal.botao;
	}
	public static void setBotao(int botao){
		TelaPrincipal.botao = botao;
	}
	public static TipoAtributoEnum getTipoAtributo(){
		return tipoAtributo;
	}
	public static void setTipoAtributo(){
		tipoAtributo = null;
	}
	public static TipoEspecializacaoEnum getTipoEspecializacao(){
		return tipoEspecializacao;
	}
	public static void setTipoEspecializacao(){
		tipoEspecializacao = null;
	}
	public static TipoEntidadeEnum getTipoEntidade(){
		return tipoEntidade;
	}
	public static void setTipoEntidade(){
		tipoEntidade = null;
	}


	private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
		((BasicInternalFrameUI)areaGrafica.getUI()).setNorthPane(null);
	}//GEN-LAST:event_formWindowActivated
	/**
	 * Método Salvar, utizado para salvar um modelo criado
	 * @param evt
	 */
	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
		JFileChooser jfc = new JFileChooser();
		jfc.setCurrentDirectory(new File(System.getProperty("user.home")));
		jfc.addChoosableFileFilter(new FileNameExtensionFilter("ConceptER Files (*.er0)", "er0"));
		jfc.setAcceptAllFileFilterUsed(true);
		
		if(StringUtils.isEmpty(PATH_FILE)) {
			if(jfc.showSaveDialog(jMenu1) == JFileChooser.APPROVE_OPTION){
				PATH_FILE = jfc.getSelectedFile().getPath() ;				
			}	
		}
		controller.save(areaGrafica, PATH_FILE);

	}//GEN-LAST:event_jMenuItem4ActionPerformed
	/**
	 * Método Novo, utilizado para criar um novo modelo
	 * @param evt
	 */
	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
		mxGraph graph = areaGrafica.getGrafico();

		mxCell root = new mxCell();
		root.insert(new mxCell());
		graph.getModel().setRoot(root);
		AreaGrafica.setCont_atributo(0);
		AreaGrafica.setCont_entidade(0);
		AreaGrafica.setCont_relacionamento(0);
		
		AreaGrafica.getMapaGraficoAgregacao().clear();
		AreaGrafica.getMapaGraficoAtributos().clear();
		AreaGrafica.getMapaGraficoEntidades().clear();
		AreaGrafica.getMapaGraficoEspecializacao().clear();
		AreaGrafica.getMapaGraficoRelacionamentos().clear();
		PATH_FILE = null;

	}//GEN-LAST:event_jMenuItem2ActionPerformed
	/**
	 * Método Abrir, utilizado para abrir um modelo já existente
	 * @param evt
	 */
	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
		JFileChooser jfc = new JFileChooser();
		jfc.setCurrentDirectory(new File(System.getProperty("user.home")));
		jfc.addChoosableFileFilter(new FileNameExtensionFilter("ConceptER Files (*.er0)", "er0"));
		jfc.setAcceptAllFileFilterUsed(true);

		if(jfc.showOpenDialog(jMenu1) == JFileChooser.APPROVE_OPTION){
			PATH_FILE = jfc.getSelectedFile().getPath();
			XmlUtils utils = new XmlUtils();
			utils.load(PATH_FILE, areaGrafica);
			//fileUtils.loadGraph(areaGrafica.getAreaGrafico(), PATH_FILE);
			firePropertyChange("currentFile", new File(""), jfc.getSelectedFile());
			
			areaGrafica.getGrafico().refresh();
		}
	}//GEN-LAST:event_jMenuItem2ActionPerformed
	/**
	 * Método Exportar Imagem, utilizado para exportar para imagem o modelo criado
	 * @param evt
	 */
	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
		JFileChooser jfc = new JFileChooser();
		
		if(jfc.showSaveDialog(jMenu1) == JFileChooser.APPROVE_OPTION){
			BufferedImage image = mxCellRenderer.createBufferedImage(areaGrafica.getGrafico(), null, 1, Color.WHITE, true, null);
			try {
				ImageIO.write(image, "PNG", new File(jfc.getSelectedFile().getPath() + ".png"));
			} catch (IOException ex) {
				Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}//GEN-LAST:event_jMenuItem7ActionPerformed

	/**
	 * Método Salvar Como, utilizado para criar um outro modelo a partir de um modelo salvo
	 * @param evt
	 */
	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
		JFileChooser jfc = new JFileChooser();
		jfc.setCurrentDirectory(new File(System.getProperty("user.home")));
		jfc.addChoosableFileFilter(new FileNameExtensionFilter("ConceptER Files (*.er0)", "er0"));
		jfc.setAcceptAllFileFilterUsed(true);
		
		if(jfc.showSaveDialog(jMenu1) == JFileChooser.APPROVE_OPTION){
			controller.save(areaGrafica, jfc.getSelectedFile().getPath());

		}
	}//GEN-LAST:event_jMenuItem5ActionPerformed

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
		if (botao == 0){
			botao = 1;
			tipoEntidade = TipoEntidadeEnum.FORTE;
		}else {
			botao = 0;
			tipoEntidade = null;
		}
	}//GEN-LAST:event_jToggleButton1ActionPerformed

	private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
		if (botao == 0){
			botao = 1;
			tipoEntidade = TipoEntidadeEnum.FRACA;
		}else {
			botao = 0;
			tipoEntidade = null;
		}
	}//GEN-LAST:event_jToggleButton2ActionPerformed

	private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
		if (botao == 0){
			botao = 2;
			tipoAtributo = TipoAtributoEnum.SIMPLES;
		}else {
			botao = 0;
			tipoAtributo = null;
		}
	}//GEN-LAST:event_jToggleButton3ActionPerformed

	private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
		if (botao == 0){
			botao = 2;
			tipoAtributo = TipoAtributoEnum.CHAVE;
		}else {
			botao = 0;
			tipoAtributo = null;
		}
	}//GEN-LAST:event_jToggleButton4ActionPerformed

	private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
		if (botao == 0){
			botao = 2;
			tipoAtributo = TipoAtributoEnum.COMPOSTO;
		}else {
			botao = 0;
			tipoAtributo = null;
		}
	}//GEN-LAST:event_jToggleButton5ActionPerformed

	private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
		if (botao == 0){
			botao = 2;
			tipoAtributo = TipoAtributoEnum.MULTIVALORADO;
		}else {
			botao = 0;
			tipoAtributo = null;
		}
	}//GEN-LAST:event_jToggleButton6ActionPerformed

	private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
		if (botao == 0){
			botao = 2;
			tipoAtributo = TipoAtributoEnum.DERIVADO;
		}else {
			botao = 0;
			tipoAtributo = null;
		}
	}//GEN-LAST:event_jToggleButton7ActionPerformed

	private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
		if (botao == 0){
			botao =3;
		}else{
			botao = 0;
		}
	}//GEN-LAST:event_jToggleButton8ActionPerformed

	private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
		if (botao == 0){
			botao =4;
		}else{
			botao = 0;
		}
	}//GEN-LAST:event_jToggleButton9ActionPerformed

	private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
		if (botao == 0){
			botao =5;
		}else{
			botao = 0;
		}
	}//GEN-LAST:event_jToggleButton10ActionPerformed

	private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
		if (botao == 0){
			botao = 6;
			tipoEspecializacao = TipoEspecializacaoEnum.DISJUNCAO;
		}else{
			botao = 0;
			tipoEspecializacao = null;
		}
	}//GEN-LAST:event_jToggleButton11ActionPerformed

	private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
		if(botao == 0){
			botao = 6;
			tipoEspecializacao = TipoEspecializacaoEnum.SOBREPOSICAO;
		}else{
			botao = 0;
			tipoEspecializacao = null;
		}
	}//GEN-LAST:event_jToggleButton12ActionPerformed

	private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
		if(botao == 0){
			botao = 7;
		}else{
			botao = 0;
		}
	}//GEN-LAST:event_jToggleButton13ActionPerformed
 /*
	private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
		if(botao == 0){
			botao = 8;
		}else{
			botao = 0;
		}
	}//GEN-LAST:event_jToggleButton14ActionPerformed

	private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
		if(botao == 0){
			botao = 9;
		}else{
			botao = 0;
		}
	}//GEN-LAST:event_jToggleButton15ActionPerformed
	*/
	private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
		if(botao == 0){
			botao = 6;
			tipoEspecializacao = TipoEspecializacaoEnum.ESPECIALIZACAO;
		}else{
			botao = 0;
			tipoEspecializacao = null;
		}
	}//GEN-LAST:event_jToggleButton12ActionPerformed

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
		TelaSobre telaSobre = new TelaSobre(this, rootPaneCheckingEnabled);
		telaSobre.setVisible(true);
	}//GEN-LAST:event_jMenuItem3ActionPerformed
	
	protected void mntmOpcoesActionPerformed(ActionEvent evt) {
		TelaOpcoes telaOpcoes = new TelaOpcoes(this, rootPaneCheckingEnabled);
		telaOpcoes.setVisible(true);	
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		//try {
			/* Set the Nimbus look and feel */
			//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
			/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
			 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
			 */
			//UIManager.setLookAndFeel(new WindowsLookAndFeel());
			//</editor-fold>
		//} catch (UnsupportedLookAndFeelException ex) {
		//	Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
		//}

		/* Create and display the form */
		/*java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new TelaPrincipal().setVisible(true);
			}
		}); */        
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        telaPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	public static void onlyOneButtonPressed(JToggleButton pressedButton) {
		List<JToggleButton> botoes = new ArrayList<JToggleButton>();
		botoes.add(jToggleButton1);
		botoes.add(jToggleButton2);
		botoes.add(jToggleButton3);
		botoes.add(jToggleButton4);
		botoes.add(jToggleButton5);
		botoes.add(jToggleButton6);
		botoes.add(jToggleButton7);
		botoes.add(jToggleButton8);
		botoes.add(jToggleButton9);
		botoes.add(jToggleButton10);
		botoes.add(jToggleButton11);
		botoes.add(jToggleButton12);
		botoes.add(jToggleButton13);
		botoes.add(jToggleButton14);
		botoes.add(jToggleButton15);
		botoes.add(jToggleButton16);
		
		if(jToggleButton1==pressedButton) {
			botoes.remove(jToggleButton1);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
			
		} else if(jToggleButton2==pressedButton) {
			botoes.remove(jToggleButton2);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton3==pressedButton) {
			botoes.remove(jToggleButton3);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton4==pressedButton) {
			botoes.remove(jToggleButton4);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton5==pressedButton) {
			botoes.remove(jToggleButton5);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton6==pressedButton) {
			botoes.remove(jToggleButton6);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton7==pressedButton) {
			botoes.remove(jToggleButton7);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton8==pressedButton) {
			botoes.remove(jToggleButton8);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton9==pressedButton) {
			botoes.remove(jToggleButton9);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton10==pressedButton) {
			botoes.remove(jToggleButton10);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton11==pressedButton) {
			botoes.remove(jToggleButton11);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton12==pressedButton) {
			botoes.remove(jToggleButton12);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton13==pressedButton) {
			botoes.remove(jToggleButton13);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton14==pressedButton) {
			botoes.remove(jToggleButton14);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		} else if(jToggleButton15==pressedButton) {
			botoes.remove(jToggleButton15);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		}  else if(jToggleButton16==pressedButton) {
			botoes.remove(jToggleButton16);
			for (JToggleButton botao : botoes) {
				botao.setSelected(false);
			}
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private br.com.concepter.view.AreaGrafica areaGrafica;
	private javax.swing.JButton jButton1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBarTelaPrincipal;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
	private javax.swing.JPopupMenu.Separator jSeparator1;
	private javax.swing.JToolBar.Separator jSeparator10;
	private javax.swing.JToolBar.Separator jSeparator11;
	private javax.swing.JToolBar.Separator jSeparator12;
	private javax.swing.JToolBar.Separator jSeparator13;
	//private javax.swing.JToolBar.Separator jSeparator14;
	//private javax.swing.JToolBar.Separator jSeparator15;
	private javax.swing.JToolBar.Separator jSeparator16;
	private javax.swing.JToolBar.Separator jSeparator17;
	private javax.swing.JToolBar.Separator jSeparator18;
	private javax.swing.JToolBar.Separator jSeparator19;
	private javax.swing.JPopupMenu.Separator jSeparator2;
	private javax.swing.JToolBar.Separator jSeparator20;
	private javax.swing.JToolBar.Separator jSeparator21;
	private javax.swing.JToolBar.Separator jSeparator22;
	private javax.swing.JToolBar.Separator jSeparator23;
	private javax.swing.JToolBar.Separator jSeparator3;
	private javax.swing.JToolBar.Separator jSeparator4;
	private javax.swing.JToolBar.Separator jSeparator5;
	private javax.swing.JToolBar.Separator jSeparator6;
	private javax.swing.JToolBar.Separator jSeparator7;
	private javax.swing.JToolBar.Separator jSeparator8;
	private javax.swing.JToolBar.Separator jSeparator9;
	private static javax.swing.JToggleButton jToggleButton1;
	private static javax.swing.JToggleButton jToggleButton10;
	private static javax.swing.JToggleButton jToggleButton11;
	private static javax.swing.JToggleButton jToggleButton12;
	private static javax.swing.JToggleButton jToggleButton13;
	private static javax.swing.JToggleButton jToggleButton14;
	private static javax.swing.JToggleButton jToggleButton15;
	private static javax.swing.JToggleButton jToggleButton16;
	private static javax.swing.JToggleButton jToggleButton2;
	private static javax.swing.JToggleButton jToggleButton3;
	private static javax.swing.JToggleButton jToggleButton4;
	private static javax.swing.JToggleButton jToggleButton5;
	private static javax.swing.JToggleButton jToggleButton6;
	private static javax.swing.JToggleButton jToggleButton7;
	private static javax.swing.JToggleButton jToggleButton8;
	private static javax.swing.JToggleButton jToggleButton9;
	private javax.swing.JToolBar jToolBar1;
	private mxGraphOutline graphOutline;
	private JMenuItem mntmOpcoes;
	// End of variables declaration//GEN-END:variables
}
