/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.concepter.view;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import com.mxgraph.util.mxCellRenderer;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;

import br.com.concepter.model.beans.Entidade;
import br.com.concepter.model.enuns.TipoAtributoEnum;
import br.com.concepter.model.enuns.TipoEntidadeEnum;
import br.com.concepter.model.enuns.TipoEspecializacaoEnum;
import br.com.concepter.utils.FileUtils;
import br.com.concepter.utils.XmlUtils;

/**
 *
 * @author AllanMagnum
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    private static int botao;
    private static TipoAtributoEnum tipoAtributo;
    private static TipoEspecializacaoEnum tipoEspecializacao;
    private static TipoEntidadeEnum tipoEntidade;
    
    
    public TelaPrincipal() {    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        areaGrafica = new br.com.concepter.view.AreaGrafica();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator22 = new javax.swing.JToolBar.Separator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jToggleButton2 = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        jToggleButton3 = new javax.swing.JToggleButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jToggleButton4 = new javax.swing.JToggleButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jToggleButton5 = new javax.swing.JToggleButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jToggleButton6 = new javax.swing.JToggleButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jToggleButton7 = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSeparator20 = new javax.swing.JToolBar.Separator();
        jToggleButton8 = new javax.swing.JToggleButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jToggleButton9 = new javax.swing.JToggleButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jToggleButton10 = new javax.swing.JToggleButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator19 = new javax.swing.JToolBar.Separator();
        jToggleButton11 = new javax.swing.JToggleButton();
        jSeparator17 = new javax.swing.JToolBar.Separator();
        jToggleButton12 = new javax.swing.JToggleButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator21 = new javax.swing.JToolBar.Separator();
        jToggleButton13 = new javax.swing.JToggleButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jToggleButton14 = new javax.swing.JToggleButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jToggleButton15 = new javax.swing.JToggleButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if(JOptionPane.showConfirmDialog(null, "Suas alterações serão perdidas se não forem salvas?") == JOptionPane.OK_OPTION){
                    setVisible(false);
                    dispose();
                }
            }
        });

        setTitle("ConceptER");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        areaGrafica.setBackground(java.awt.Color.white);
        areaGrafica.setBorder(null);
        areaGrafica.setForeground(new java.awt.Color(255, 255, 255));
        areaGrafica.setPreferredSize(new java.awt.Dimension(400, 200));
        areaGrafica.setVisible(true);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setAlignmentY(0.0F);
        jToolBar1.setMinimumSize(new java.awt.Dimension(40, 349));
        jToolBar1.setPreferredSize(new java.awt.Dimension(40, 397));
        jToolBar1.add(jSeparator22);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retanguloo.jpg"))); // NOI18N
        jToggleButton1.setToolTipText("Entidade");
        jToggleButton1.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);
        jToolBar1.add(jSeparator8);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retangulo.png"))); // NOI18N
        jToggleButton2.setToolTipText("Entidade Fraca");
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton2);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator18);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Circulo.png"))); // NOI18N
        jToggleButton3.setToolTipText("Atributo Simples");
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton3);
        jToolBar1.add(jSeparator10);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Circulo com traço.png"))); // NOI18N
        jToggleButton4.setToolTipText("Atributo Chave");
        jToggleButton4.setFocusable(false);
        jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton4.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton4);
        jToolBar1.add(jSeparator11);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/3 balões.png"))); // NOI18N
        jToggleButton5.setToolTipText("Atributo Composto");
        jToggleButton5.setFocusable(false);
        jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton5.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton5);
        jToolBar1.add(jSeparator7);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Circulo dentro.png"))); // NOI18N
        jToggleButton6.setToolTipText("Atributo Multivalorado");
        jToggleButton6.setFocusable(false);
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton6);
        jToolBar1.add(jSeparator9);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Circulo tracejado.png"))); // NOI18N
        jToggleButton7.setToolTipText("Atributo Derivado");
        jToggleButton7.setFocusable(false);
        jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton7.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton7);
        jToolBar1.add(jSeparator4);
        jToolBar1.add(jSeparator20);

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/binario.png"))); // NOI18N
        jToggleButton8.setToolTipText("Relacionamento Binário");
        jToggleButton8.setFocusable(false);
        jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton8.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton8);
        jToolBar1.add(jSeparator13);

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/ternario.png"))); // NOI18N
        jToggleButton9.setToolTipText("Relacionamento Ternário");
        jToggleButton9.setFocusable(false);
        jToggleButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton9.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton9);
        jToolBar1.add(jSeparator12);

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/quaternario.png"))); // NOI18N
        jToggleButton10.setToolTipText("Relacionamento Quaternário");
        jToggleButton10.setFocusable(false);
        jToggleButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton10.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton10);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator19);

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Círculo C.png"))); // NOI18N
        jToggleButton11.setToolTipText("Disjunção");
        jToggleButton11.setFocusable(false);
        jToggleButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton11.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton11);
        jToolBar1.add(jSeparator17);

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Círculo O.png"))); // NOI18N
        jToggleButton12.setToolTipText("Sobreposição");
        jToggleButton12.setFocusable(false);
        jToggleButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton12.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton12);
        jToolBar1.add(jSeparator6);
        jToolBar1.add(jSeparator21);

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retangulo losango.jpg"))); // NOI18N
        jToggleButton13.setToolTipText("Agregação Binária");
        jToggleButton13.setFocusable(false);
        jToggleButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton13.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton13);
        jToolBar1.add(jSeparator16);

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retangulo losango.jpg"))); // NOI18N
        jToggleButton14.setToolTipText("Agregação Ternária");
        jToggleButton14.setFocusable(false);
        jToggleButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton14.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton14);
        jToolBar1.add(jSeparator15);

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/concepter/view/resources/imagens/Retangulo losango.jpg"))); // NOI18N
        jToggleButton15.setToolTipText("Agregação Quaternária");
        jToggleButton15.setFocusable(false);
        jToggleButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton15.setPreferredSize(new java.awt.Dimension(34, 23));
        jToggleButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton15);
        jToolBar1.add(jSeparator14);

        jMenu1.setLabel("Arquivo");

        jMenuItem1.setText("Novo");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Abrir ...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Salvar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Salvar como ...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator1);

        jMenuItem7.setText("Exportar imagem ...");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator2);

        jMenuItem8.setText("Sair");
        jMenu1.add(jMenuItem8);

        jMenuBarTelaPrincipal.add(jMenu1);

        jMenu2.setText("Ferramenta");

        jMenu6.setText("Opções");

        jMenu4.setText("Grade");

        jCheckBoxMenuItem1.setText("Sem");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setText("Com");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem2);

        jMenu6.add(jMenu4);

        jMenu2.add(jMenu6);

        jMenuBarTelaPrincipal.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBarTelaPrincipal.add(jMenu3);

        setJMenuBar(jMenuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(areaGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public static void desclicarBotoes(){
        TelaPrincipal.jToggleButton1.setSelected(false);
        TelaPrincipal.jToggleButton2.setSelected(false);
        TelaPrincipal.jToggleButton3.setSelected(false);
        TelaPrincipal.jToggleButton4.setSelected(false);
        TelaPrincipal.jToggleButton5.setSelected(false);
        TelaPrincipal.jToggleButton6.setSelected(false);
        TelaPrincipal.jToggleButton7.setSelected(false);
        TelaPrincipal.jToggleButton8.setSelected(false);
        TelaPrincipal.jToggleButton9.setSelected(false);
        TelaPrincipal.jToggleButton10.setSelected(false);
        TelaPrincipal.jToggleButton11.setSelected(false);
        TelaPrincipal.jToggleButton12.setSelected(false);
        TelaPrincipal.jToggleButton13.setSelected(false);
        TelaPrincipal.jToggleButton14.setSelected(false);
        TelaPrincipal.jToggleButton15.setSelected(false);
    }
    
    public static int getBotao(){
        return TelaPrincipal.botao;
    }
    public static void setBotao(int botao){
        TelaPrincipal.botao = botao;
    }
    public static TipoAtributoEnum getTipoAtributo(){
        return tipoAtributo;
    }
    public static void setTipoAtributo(){
        tipoAtributo = null;
    }
    public static TipoEspecializacaoEnum getTipoEspecializacao(){
        return tipoEspecializacao;
    }
    public static void setTipoEspecializacao(){
        tipoEspecializacao = null;
    }
    public static TipoEntidadeEnum getTipoEntidade(){
        return tipoEntidade;
    }
    public static void setTipoEntidade(){
        tipoEntidade = null;
    }
    
   
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ((BasicInternalFrameUI)areaGrafica.getUI()).setNorthPane(null);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFileChooser jfc = new JFileChooser();
        
        FileUtils fileUtils = new FileUtils();
        
        XmlUtils xmlUtils = new XmlUtils();
        
        if(jfc.showSaveDialog(jMenu1) == JFileChooser.APPROVE_OPTION){
            fileUtils.saveGraph(areaGrafica.getAreaGrafico(), jfc.getSelectedFile().getPath());
            
            List<Entidade> entidades = new ArrayList<Entidade>();
            
            for (Integer key : areaGrafica.getMapaGraficoEntidades().keySet()) {
                    
                Entidade entidade = areaGrafica.getMapaGraficoEntidades().get(key);
                
                entidades.add(entidade);           
            } 
            
            try {
                FileOutputStream os = new FileOutputStream(jfc.getSelectedFile().getPath() + ".xml" );
                xmlUtils.save( entidades, os);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileUtils fileUtils = new FileUtils();
        
        if(jfc.showOpenDialog(jMenu1) == JFileChooser.APPROVE_OPTION){    
            fileUtils.loadGraph(areaGrafica.getAreaGrafico(), jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JFileChooser jfc = new JFileChooser();
        
        FileUtils fileUtils = new FileUtils();
        
        if(jfc.showSaveDialog(jMenu1) == JFileChooser.APPROVE_OPTION){
            BufferedImage image = mxCellRenderer.createBufferedImage(areaGrafica.getGrafico(), null, 1, Color.WHITE, true, null);
            try {
                ImageIO.write(image, "PNG", new File(jfc.getSelectedFile().getPath() + ".png"));
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (botao == 0){
            botao = 1;
            tipoEntidade = tipoEntidade.FORTE;
        }else {
            botao = 0;
            tipoEntidade = null;
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (botao == 0){
            botao = 1;
            tipoEntidade = tipoEntidade.FRACA;
        }else {
            botao = 0;
            tipoEntidade = null;
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if (botao == 0){
            botao = 2;
            tipoAtributo = tipoAtributo.SIMPLES;
        }else {
            botao = 0;
            tipoAtributo = null;
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        if (botao == 0){
            botao = 2;
            tipoAtributo = tipoAtributo.CHAVE;
        }else {
            botao = 0;
            tipoAtributo = null;
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if (botao == 0){
            botao = 2;
            tipoAtributo = tipoAtributo.COMPOSTO;
        }else {
            botao = 0;
            tipoAtributo = null;
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        if (botao == 0){
            botao = 2;
            tipoAtributo = tipoAtributo.MULTIVALORADO;
        }else {
            botao = 0;
            tipoAtributo = null;
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        if (botao == 0){
            botao = 2;
            tipoAtributo = tipoAtributo.DERIVADO;
        }else {
            botao = 0;
            tipoAtributo = null;
        }
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        if (botao == 0){
            botao =3;
        }else{
            botao = 0;
        }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        if (botao == 0){
            botao =4;
        }else{
            botao = 0;
        }
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        if (botao == 0){
            botao =5;
        }else{
            botao = 0;
        }
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        if (botao == 0){
            botao = 6;
            tipoEspecializacao = tipoEspecializacao.DISJUNCAO;
        }else{
            botao = 0;
            tipoEspecializacao = null;
        }
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        if(botao == 0){
            botao = 6;
            tipoEspecializacao = tipoEspecializacao.SOBREPOSICAO;
        }else{
            botao = 0;
            tipoEspecializacao = null;
        }
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        if(botao == 0){
            botao = 7;
        }else{
            botao = 0;
        }
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        if(botao == 0){
            botao = 8;
        }else{
            botao = 0;
        }
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        if(botao == 0){
            botao = 9;
        }else{
            botao = 0;
        }
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaSobre telaSobre = new TelaSobre(this, rootPaneCheckingEnabled);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        jCheckBoxMenuItem2.setSelected(false);
        areaGrafica.preencherGrade(0L);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        jCheckBoxMenuItem1.setSelected(false);
        areaGrafica.preencherGrade(1L);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
            //</editor-fold>
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.concepter.view.AreaGrafica areaGrafica;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBarTelaPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator20;
    private javax.swing.JToolBar.Separator jSeparator21;
    private javax.swing.JToolBar.Separator jSeparator22;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private static javax.swing.JToggleButton jToggleButton1;
    private static javax.swing.JToggleButton jToggleButton10;
    private static javax.swing.JToggleButton jToggleButton11;
    private static javax.swing.JToggleButton jToggleButton12;
    private static javax.swing.JToggleButton jToggleButton13;
    private static javax.swing.JToggleButton jToggleButton14;
    private static javax.swing.JToggleButton jToggleButton15;
    private static javax.swing.JToggleButton jToggleButton2;
    private static javax.swing.JToggleButton jToggleButton3;
    private static javax.swing.JToggleButton jToggleButton4;
    private static javax.swing.JToggleButton jToggleButton5;
    private static javax.swing.JToggleButton jToggleButton6;
    private static javax.swing.JToggleButton jToggleButton7;
    private static javax.swing.JToggleButton jToggleButton8;
    private static javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
